const CmsContext = {
  language: 'en-US',
  landingPage: {
    'cookie.more': "Customize",
    'cookie.title': "We're using cookies",
    'app.user_management': 'User Management',
    'home.media_ecosystem': 'Media Ecosystem',
    'help.title': 'Recommended help',
    'help.more': 'Read more',
    'browser.incompatible': "We're very sorry, but your browser is not supported! For the best experience, please upgrade to a supported browser.",
    'help.articles': 'Top frequently asked questions',
    'cookie.consent': 'Our apps tick along thanks to some basic necessary cookies. To improve things even more, we’d like your consent to add some optional cookies that will share your user behaviour with our analytics service providers, Google Analytics and FullStory. If you’d like to adjust your preferences or find out more about it, see our Cookies Policy.We won\'t set optional cookies unless you enable them.',
    'cookie.accept': 'Accept cookies',
    'cookie.reject': "Don't accept",
    'home.welcome': 'Welcome to',
    'network.offline': 'Looks like we\'re having connection issues. Please check your internet connection.',
    'help.feedback': 'Provide feedback',
    'app.plan_manager': 'Plan Manager',
    'home.introduction': ' secure suite of applications that help drive the data quality and operational efficiency of our business at Dentsu (that hopefully make your day-to-day lives easier.)',
    'help.centre': 'Help centre',
    'footer.settings': 'Cookie Settings',
    'notifications.title': 'Notifications',
    'app.home': 'Media Ecosystem',
    'app.demo_data_management': 'Demo Data Manager',
    'language.zh-hant': '繁體中文 (Chinese - Traditional)',
    'CLM_instruction': 'Manage the full life cycle of a client; from getting new clients on to (Media Ecosystem name), editing their account settings and archiving and removing them at the end of a contract life.',
    'user_management.title': 'User Management',
    'global_apps.heading': 'Apps to help you manage your clients and teams',
    'app.client_management': 'Client Management',
    'user_management.manage': 'Manage users',
    'client_management.title': 'Client Management',
    'language.en': 'English',
    'language.fr': 'Français (French)',
    'language.ja': '日本語 (Japanese)',
    'footer.cookies': 'Cookie Policy',
    'notifications.empty': 'No new notifications',
    'app.taxonomy_manager': 'Taxonomy Manager',
    'footer.terms': 'Terms of Use',
    'footer.privacy': 'Privacy Policy',
    'app.taxonomy_name_generator': 'Taxonomy Name Generator',
    'USM_instruction': 'Manage users for all the clients you have access to, to make sure the right people have the correct access and permissions to the right applications.',
    'language.zh-hans': '简体中文 (Chinese - Simplified)',
    'app.data_refinery': 'Data Refinery',
    'clients_apps.instruction': 'Select a client and application to show which accounts are available',
    'client_management.manage': 'Manage clients',
    'client.select_account': 'Select an account',
    'action.logout': 'Logout',
    'client.select_app': 'Select an application',
    'client.launch': 'Launch app',
    'clients_apps.title': 'Clients and applications',
    'clients_apps.no_access_instruction': 'Clients will appear here once they have been fully onboarded.If you\'re a part of the onboarding process, head over to the Client Management app using the right-hand side link.',
    'client.available_accounts': '24 accounts available',
    'translation.unavailable': 'This application is not yet available in this language. We make every effort to offer our application in more languages and will provide you with the translated version as soon as it becomes available.',
    'clients_apps.no_access_title': 'You don\'t have access to any onboarded clients.',
    'client.select': 'Select client',
    'terms.information_head_2': 'The information and data contained here may not be discussed, shared, copied, or distributed to parties, organizations, electronic mail accounts, or storage devices that are outside of Dentsu Aegis Network. Any reports generated may accessed through the supported data visualisation tools.',
    'terms.cred_warning_1': 'You must treat your user credentials, password and any other piece of information required as part of our security procedures as confidential and you must not disclose them to any other Dentsu Aegis Network employee, or any third party.',
    'terms.title': 'Terms of Use',
    'terms.information_list_1': 'rent, lease, sub-license, loan, translate, adapt or modify in any way, the whole or any part of the application; and',
    'terms.warning': 'Failure to abide by these conditions will lead to serious disciplinary action, including suspension of access, termination of employment and other legal proceedings.',
    'terms.agree': 'I agree',
    'terms.information_list_2': 'disassemble, de-compile, reverse engineer or create derivative works based on the whole or any part of the application unless permitted to do so by applicable law.',
    'market.select': 'Select market',
    'terms.information_head_1': 'The information and data contained within this application are the property of Dentsu Aegis Network and our licensors and is highly confidential.",',
    'help.readme': 'This readme is really dragging on...',
    'terms.cred_warning_2': 'If you become aware that your user credentials and/or password have become compromised, you are required to contact compliance@dentsuaegis.com immediately.',
    'terms.confirm_data': 'By using this application you confirm that you have read and understood these conditions of use and you agree to comply with them. If you do not agree to these conditions of use, you must not continue to use this application.',
    'notFound.message': 'Sorry something wrong',
    'terms.information_head_3': 'The application and all intellectual property rights in the application belong to Dentsu Aegis Network. You must not:',
    'notification_management.title': 'Notification Manager',
    'NTM_instruction': 'Manage the messages, channels and recipients of notifications',
    'notification_management.manage': 'Manage Notifications',
    'TXM_description': 'Helps you classify and control your client data at source, to ensure data is accurate and up-to-date for the other apps to use',
    'TXG_description': "Create accurate name strings to help you easily traffic all your client's campaigns",
    'CLM_description': 'Oversee the full life-cycle of your client from onboarding to the day-to-day management of client, vendor and market data',
    'DRF_description': 'Gather, clean and transform all performance data so you can efficiently report, optimise and draw insight for your client',
    'PLM_description': 'Making the briefing process easier and more transparent, to better connect planning and buying teams',
    'USM_description': 'Manage your teams app permissions, so that the right users have the right tools to do their jobs',
    'NTM_description': 'Manage the messages, channels and recipients of notifications',
    'DDM_instruction': 'Manages the demo clients data i.e. updating and restoring the client data, undo onboarding of the clients.',
    'DDM_description': 'Manages the demo clients data i.e. updating and restoring the client data, undo onboarding of the clients.',
  }, '__typename': 'strapiOutput',

};
module.exports = CmsContext;
