const CmsContext = {
  language: 'en-GB',

  globalshells: {
    'CLM_description': 'Oversee the full life-cycle of your client from onboarding to the day-to-day management of client, vendor and market data',
    'DDM_description': 'Manages the demo clients data i.e. updating and restoring the client data, undo onboarding of the clients.',
    'DRF_description': 'Gather, clean and transform all performance data so you can efficiently report, optimise and draw insight for your client',
    'Dashboard_description': 'Manage all your conventions in one place for your client',
    'NTM_description': 'Manage the messages, channels and recipients of notifications',
    'PLM_description': 'Making the briefing process easier and more transparent, to better connect planning and buying teams',
    'TLB_description': 'Tools Library houses our catalogue of available research tools for DAN brands in each market. Tools can be filtered by insight type, market and data.',
    'TVS_description': 'Create planning scenarios to help optimise your budget across different video channel.',
    'TXG_description': 'Create accurate name strings to help you easily traffic all your client\'s campaigns',
    'TXM_description': 'Helps you classify and control your client data at source, to ensure data is accurate and up-to-date for the other apps to use',
    'USM_description': 'Manage your teams app permissions, so that the right users have the right tools to do their jobs',
    'action.logout': 'Logout',
    'app.client_management': 'Client Management',
    'app.data_refinery': 'Data Refinery',
    'app.demo_data_management': 'Demo Data Manager',
    'app.home': 'Media Ecosystem',
    'app.client_workflow': 'Media Ecosystem',
    'home.welcome': 'Welcome to',
    'app.plan_manager': 'Plan Manager',
    'app.taxonomy_manager': 'Taxonomy Manager',
    'app.taxonomy_name_generator': 'Taxonomy Name Generator',
    'app.tv_stack': 'Tv Stack',
    'app.user_management': 'User Management',
    'browser.incompatible': 'We\'re very sorry, but your browser is not supported! For the best experience, please upgrade to a supported browser.',
    'client.available_accounts': '24 accounts available',
    'client.launch': 'Launch app',
    'client.select': 'Select a client',
    'client.select_account': 'Select an account',
    'client.select_app': 'Select an app',
    'client_management.instruction': 'Manage the full life cycle of a client; from getting new clients on to (Media Ecosystem name), editing their account settings and archiving and removing them at the end of a contract life.',
    'client_management.manage': 'Manage clients',
    'client_management.title': 'Client Management',
    'clients_apps.error_instruction': 'That\'s ok, it could be that you\'re only working on apps that aren\'t viewed through the client lens. If you have any client specific apps added, they will appear here.',
    'clients_apps.error_instruction_newUI': 'That\'s ok, it could be that you\'re only working on apps that aren\'t viewed through the client lens. If you have any client specific apps added, they will appear here.',
    'clients_apps.error_title': 'You don\'t have any client apps',
    'clients_apps.error_title_newUI': 'You don\'t have any client apps',
    'clients_apps.instruction': 'Select a client and application to show which accounts are available',
    'clients_apps.no_access_instruction': 'Clients will appear here once they have been fully onboarded.If you\'re a part of the onboarding process, head over to the Client Management app using the right-hand side link.',
    'clients_apps.no_access_instruction_newUI': 'Get started adding your first client now in the Client Management app.',
    'clients_apps.no_access_title': 'You don\'t have access to any onboarded clients.',
    'clients_apps.no_access_title_newUI': 'You don\'t have any client apps',
    'clients_apps.title': 'Clients and applications',
    'cookie.accept': 'Accept cookies',
    'cookie.consent': 'Our apps tick along thanks to some basic necessary cookies. To improve things even more, we’d like your consent to add some optional cookies that will share your user behaviour with our analytics service providers, Google Analytics and FullStory. If you’d like to adjust your preferences or find out more about it, see our Cookies Policy.<br /><br />We won\'t set optional cookies unless you enable them.',
    'cookie.more': 'Customize',
    'cookie.reject': 'Don\'t accept',
    'cookie.title': 'We\'re using cookies',
    'cookies_GAlink': 'You can find out more about Google Analytics cookies',
    'cookies_fullStoryLink': 'You can find out more about FullStory cookies',
    'cookies_heading': 'Cookie Policy',
    'cookies_here': 'here',
    'cookies_paragraph_1': 'Cookies are small packets of information stored by your web browser when you visit certain websites, including Media Ecosystem. Cookies are generally used by websites and applications to improve your experience by enabling that website to ‘remember’ you, either only for the duration of your visit (using a “Session” cookie which is deleted when you close your browser) or for repeat visits (using a “Permanent” cookie).',
    'cookies_subHeading_1': 'How we deploy "cookies',
    'cookies_table1_c3_r1': 'Okta uses an HTTP session cookie to give access to and authenticate access to Media Ecosystem across web requests for interactive user-agents like, for example, a browser.',
    'cookies_table1_c3_r2': 'Okta uses an HTTP session cookie to give access to and authenticate access to Media Ecosystem across web requests for interactive user-agents like, for example, a browser.',
    'cookies_table1_c3_r3': 'Required for the Jira Issue Collector. This cookie stores users preferences for the Atlassian text editor.',
    'cookies_table1_c3_r4': 'Required for the Jira Issue Collector. This cookie helps to prevent XSRF attacks. During a user\'s session, this cookie ensures that browser requests sent to an Atlassian Cloud instance are originated from that Cloud instance.',
    'cookies_table1_c3_r5': 'Required for the Jira Issue Collector. This cookie contains a random string which is used for session tracking.',
    'cookies_table1_heading_c1': 'Cookie name',
    'cookies_table1_heading_c2': 'Cookie expiry period',
    'cookies_table1_heading_c3': 'Purpose',
    'cookies_table2_c2_r1': '2 years from set/update',
    'cookies_table2_c2_r2': '30 mins from set/update',
    'cookies_table2_c2_r5': '18 months',
    'cookies_table2_c2_r6': '6 months from set/update',
    'cookies_table2_c3_r1': 'Unique visitor cookies : Used to distinguish users and sessions. The cookie is created when the JavaScript library executes and no existing __utma cookies exists. The cookie is updated every time data is sent to Google Analytics.',
    'cookies_table2_c3_r2': 'Session cookie : Used to determine new sessions/visits. The cookie is created when the JavaScript library executes and no existing __utmb cookies exists. The cookie is updated every time data is sent to Google Analytics.',
    'cookies_table2_c3_r3': 'Session cookie : Not used in ga.js. Set for interoperability with urchin.js (an older JavaScript measurement library associated with Google Analytics). Historically, this cookie operated in conjunction with the __utmb cookie to determine whether the user was in a new session/visit.',
    'cookies_table2_c3_r4': 'Visitor segmentation cookie : Not used in ga.js. Set for interoperability with urchin.js. Historically, this cookie operated in conjunction with the __utmb cookie to determine whether the user was in a new session/visit.',
    'cookies_table2_c3_r5': 'Google Analytics Content Experiment cookie : Used to determine a user\'s inclusion in an experiment, which allows us to test changes to the application.',
    'cookies_table2_c3_r6': 'Campaign cookie : Stores the traffic source or campaign that explains how the user reached your site. The cookie is created when the JavaScript library executes and is updated every time data is sent to Google Analytics.',
    'cookies_table3_c2_r1': '1 year from set/update',
    'cookies_table3_c3_r1': 'This is a first party cookie and is used to group sessions together by users. This helps ensure that anonymous sessions are brought together for the same user on return visits to your site.',
    'cookies_table_end_session': 'End of browser session',
    'cookies_type1_heading': 'Strictly necessary cookies',
    'cookies_type1_jiraLink': 'You can find out more about Jira/Atlassian cookies ',
    'cookies_type1_oktaLink': 'You can find out more about Okta cookies ',
    'cookies_type1_paragraph_1': 'We switch on cookies to make sure the Media Ecosystem works smoothly, and to provide secure access to this application. We use an Okta and Jira/Atlassian cookie-based authentication mechanism for this purpose.',
    'cookies_type1_paragraph_2': 'Our strictly necessary cookies are listed below:',
    'cookies_type2_heading': 'Performance cookies',
    'cookies_type2_paragraph_1': 'We\'d like to set Google Analytics and FullStory cookies to help us to improve Media Ecosystem by collecting and reporting information on how you use it. We use these third-party cookies to track how you to interact with and use this application. The cookies collect information in an anonymous form, including where you have come to Media Ecosystem from, the pages you visit and how you interact with Media Ecosystem. All of this useful information helps us better understand how Media Ecosystem can be improved to further meet the needs of you, our users.',
    'cookies_type2_paragraph_2': 'These cookies don’t collect any information that allows us to identify a visitor, we only receive aggregate level data which we use to improve how the site works.',
    'cookies_type2_paragraph_3': 'We won\'t set performance cookies unless you enable them.',
    'cookies_type2_paragraph_4': 'Our performance cookies are listed below:',
    'cookies_type2_subHeading1': 'Google Analytics',
    'cookies_type2_subHeading2': 'FullStory',
    'cookies_type3_and': 'and',
    'cookies_type3_heading': 'How to reject cookies',
    'cookies_type3_link1': 'To find out more, please consult the following:',
    'cookies_type3_paragraph_1': 'If you no longer want to receive performance cookies, simply deselect performance cookies on the above toggle.',
    'cookies_type3_paragraph_2': 'If you no longer wish to receive any cookies, you can alter your browser settings, however, doing so may affect the performance of the Media Ecosystem.',
    'cookies_type3_paragraph_3': 'The procedure of turning off all cookies varies from one browser application to another. If you\'d like to reject cookies from Media Ecosystem, but wish to accept those from other sites, you can choose the option in your browser settings to receive a notice before a cookie is stored on your device. Please consult the “Help” section of your browser for more information.',
    'cookies_type3_paragraph_4': '. By disabling cookies, you can be prevented from accessing some features of our site or certain content or functionality may not be available.',
    'cookies_type_heading': 'Media Ecosystem uses two types of cookies:',
    'cookies_type_point_1': 'Strictly necessary cookies',
    'cookies_type_point_2': 'Performance cookies',
    'demoDataManager': 'manages demo clients updation.',
    'demo_data_management.instruction': 'Manages the demo clients data i.e. updating and restoring the client data, undo onboarding of the clients.',
    'demo_data_management.manage': 'Demo Data Manager',
    'demo_data_management.title': 'Demo Data Manager',
    'footer.cookies': 'Cookie policy',
    'footer.privacy': 'Privacy policy',
    'footer.settings': 'Cookie settings',
    'footer.terms': 'Terms of use',
    'global_apps.heading': 'Apps to help you manage your clients and teams',
    'help.articles': 'Top frequently asked questions',
    'help.centre': 'Help centre',
    'help.feedback': 'Provide feedback',
    'help.more': 'Read more',
    'help.readme': 'This readme is really dragging on...',
    'help.title': 'Recommended help',
    'home.introduction': ' secure suite of applications that help drive the data quality and operational efficiency of our business at Dentsu (that hopefully make your day-to-day lives easier.)',
    'home.media_ecosystem': 'Media Ecosystem',
    'home.tab_search_title': 'Filter by search',
    'home.welcome': 'Welcome to',
    'language.en': 'English',
    'language.fr': 'Français (French)',
    'language.ja': '日本語 (Japanese)',
    'language.zh-hans': '简体中文 (Chinese - Simplified)',
    'language.zh-hant': '繁體中文 (Chinese - Traditional)',
    'market.select': 'Select an account',
    'network.offline': 'Looks like we\'re having connection issues. Please check your internet connection.',
    'notFound.message': 'Sorry something wrong',
    'notification_management.instruction': 'Manage the messages, channels and recipients of notifications',
    'notification_management.manage': 'Manage Notifications',
    'notification_management.title': 'Notification Manager',
    'notifications.empty': 'No new notifications',
    'notifications.title': 'Notifications',
    'terms.agree': 'I agree',
    'terms.confirm_data': 'By using this application you confirm that you have read and understood these conditions of use and you agree to comply with them. If you do not agree to these conditions of use, you must not continue to use this application.',
    'terms.cred_warning_1': 'You must treat your user credentials, password and any other piece of information required as part of our security procedures as confidential and you must not disclose them to any other Dentsu Aegis Network employee, or any third party.',
    'terms.cred_warning_2': 'If you become aware that your user credentials and/or password have become compromised, you are required to contact compliance@dentsuaegis.com immediately.',
    'terms.information_head_1': 'The information and data contained within this application are the property of Dentsu Aegis Network and our licensors and is highly confidential.',
    'terms.information_head_2': 'The information and data contained here may not be discussed, shared, copied, or distributed to parties, organizations, electronic mail accounts, or storage devices that are outside of Dentsu Aegis Network. Any reports generated may accessed through the supported data visualisation tools.',
    'terms.information_head_3': 'The application and all intellectual property rights in the application belong to Dentsu Aegis Network. You must not:',
    'terms.information_list_1': 'rent, lease, sub-license, loan, translate, adapt or modify in any way, the whole or any part of the application; and',
    'terms.information_list_2': 'disassemble, de-compile, reverse engineer or create derivative works based on the whole or any part of the application unless permitted to do so by applicable law.',
    'terms.title': 'Terms of use',
    'terms.warning': 'Failure to abide by these conditions will lead to serious disciplinary action, including suspension of access, termination of employment and other legal proceedings.',
    'tools_library.instruction': 'Tools Library houses our catalogue of available research tools for DAN brands in each market. Tools can be filtered by insight type, market and data.',
    'tools_library.manage': 'Tools Library',
    'tools_library.title': 'Tools Library',
    'translation.unavailable': 'This application is not yet available in this language. We make every effort to offer our application in more languages and will provide you with the translated version as soon as it becomes available.',
    'userManagement': 'It manages the user access if the application.',
    'user_management.instruction': 'Manage users for all the clients you have access to, to make sure the right people have the correct access and permissions to the right applications.',
    'user_management.manage': 'Manage users',
    'user_management.title': 'User Management',
  },

  emptyStateText: {
    clientDetails: 'You don’t have any client details yet. Once the Client Lead has added them, you’ll be able to find them in this section.',
    datagovernance: 'You don’t have any data governance yet. Once the Data Governance Lead has added it in, you’ll be able to find it here.',
    accountSettings: 'Once the Account Lead has added them, you’ll be able to find them in this section.',
    activeScreenText: 'Accounts appear here as soon as a legal authoriser approves client and data governance details.',
  },


  onBoarding: {
    backToYourActiveClients: 'Back to your active clients',
    updateBannerHeader: 'is ready to go live',
    updateBannerText1: 'The following markets',
    updateBannerText2: 'have been added. Check you’re happy with the changes before updating.',
    updateButton: 'Update now',
    goLiveText: 'is ready to go live',
    goLiveBannerText: `to add the client to the Media Ecosystem so other apps can get started`,
    goLiveButton: 'Go Live',
    goLiveMessage: 'is now live in the Media Ecosystem.',
  },

  dataGovernance: {
    headerText: `Get set, go!`,
    subHeader: `s data according to their contract`,
    helpTest: `s data according to the contract. You might need some support from the legal team to complete this.`,
    make_sure: `Make sure:`,
    summaryOne: `You have either the actual client contract or a contract summary`,
    summaryTwo: `The record is accurate (It is your responsibility to ensure this record is accurate which will be reviewed by the authorisers opposite)`,
    startDGButtonText: `Get started`,
    stepOneStepperText: `Using campaign data`,
    stepOneHeaderText: `How are Dentsu Aegis Network and its agencies allowed to use campaign data`,
    stepOneHelpText: `re not sure and think you might need some assistance, please ask the legal counsel for your region or market.`,
    questionOne: `Dentsu Aegis Network and its agencies will use campaign data ?`,
    questionOneOptionOne: `ONLY for the provision of services to the client`,
    questionOneOptionTwo: `Provision of services to the client, PLUS the following additional benefits`,
    subOptionOne: `For internal business purposes of Dentsu Aegis Network and its agencies`,
    subOptionTwo: `To enhance the products and services of Dentsu Aegis Network and its agencies`,
    subOptionThree: `To generate market data and insights`,
    questionTwo: `Are there any restrictions on where campaign data will be stored ?`,
    questionTwoOptionTwo: `Select the restricted locations data CAN be stored`,
    yes: `Yes`,
    no: `No`,
    questionThree: `Are there any other restrictions around the storing or accessing of data (that are not covered by the clauses above)?`,
    questionThreeOptionTwo: `Please specify any additional restriction`,
    questionThreeOption3HelpText: `We want to make sure we cater for all requirements. So, if you know of any data governance restrictions we may have missed in this section, please let us know.`,
    questionFour: `For how long should campaign data be retained following termination or expiry of a client contract?`,
    questionFourOtherText: `If Other, please specify`,
    stepTwoStepperText: `Review`,
    declaration: `Declaration`,
    declarationText: `I have checked the above information is accurate, and understand by onboarding this client it means that Dentsu Aegis Network will store campaign data in the [Media Ecosystem] platform.`,
    textFieldErrorMessage: 'Please provide a valid text',
    textInputErrMessage1: `Number should be between 0 to 100 `,
    textInputErrMessage2: `Invalid number `,
  },

  clientPolicy: {
    welcome: 'Welcome to',
    headerCM1: 'Client Management',
    headerCM2: 'Management',
    clientSection1: 'This collaborative tool allows you to add new clients to media ecosystem and track progress of the setup working with finance and legal.',
    // clientSection2:" setting, as well as new clients and track and",
    // clientSection3:"monitor the setup process",
    beforeStart: 'Before you start, make sure you have:',
    questionStart1: 'We will ask you 3 questions that determine the type of setup you will need for this client. Make sure you have:',
    questionStart2: ' setup you will need for this client. Make sure you have:',
    requirement1: 'A client contract has been created by legal',
    requirement1a: 'A contract must exist to set up a client',
    requirement2: 'The terms of the agreement',
    requirement2a: 'In particular which agency(s) will be working on this client, whether they are covered by the legal agreement, the type of contract in place and the length of contract',
    requirement3a: 'The financial BPC SAP code',
    requirement3b: 'The Business Planning and Consolidation code is where the business costs for this client will be attributed to. Normally, your finance team will know straight away — so ask, or find out more on Neon.',
    question1: 'Is this a global or local (domestic) client?',
    question2: 'What kind of contract do you have for this global client?',
    question3: 'Where is the lead agency for this client based?',
    clientHeader: 'Client details',
    clientSubHead: 'store the basic details about client',
    clientContent: 'From the agencies working on the account, to the terms of the contract, here you store the basic details about the client.',
    clientAgencyHeader: 'Client and Agency brand details',
    aboutClient: 'About this client',
    aboutClientInfo: 'What sector is this client?',
    countries: 'What countries will this client operate in?',
    countriesInfo: 'Each country will represent an individual operational account for this client.',
    leadAgencyBrand: 'Lead agency brand',
    leadAgencyInfo: '(The agency represented in the master agreement)',
    BPC: 'BPC SAP code for finance',
    BPCInfo: 'The Business Planning and Consolidation Code - is where the business costs for this client will be attributed to.',
    suppAgencyBrand: 'Supporting agency brand(s)',
    suppAgencyInfo: 'Do you have any supporting agencies explicitly stated in the contract?',
    stepStatus: '1 step closer, 3 to go!',
    babySteps: '(baby steps)',
    step1Detail: 'Your progress has been saved to date, and you can come back later to pick up where you left off.',
    addClient: 'Add a new client',
    typeOfClient: 'Type of client',
    regionWorkRunFrom: 'Dentsu Aegis Network office this work will be operationally run from',
    supAgency: 'Supporting agency brand',
    supAgencyBrand: 'Supporting agencies',
    clientAgreements: 'Agreement',
    terms: 'The terms',
    durationOfContract: 'Duration of contract',
    durationType: 'Duration type',
    startDate: 'Start date',
    endDate: 'End date',
    selectDate: 'Select',
    end_Date: 'End date',
    contactDetails: 'Client\'s contact details at Aura Skin',
    submittedClientData: 've submitted client details',
    submitInfo: 'done their bit, the information will be reviewed by your designated ',
    submittedGovernanceData: 've submitted Client Data Governance details',
    data: '(This is what we mean when we say "data")',
    dataDetail: 'we use this as a general term to call all of the campaign data that',
    generatedData1: 'Generated data',
    generatedDataDetail: 'TBC copy goes here (e.g. Example goes here too to bring to life the definition)',
    combinedData: 'Combined data',
    combinedDataDetail: 'TBC copy goes here (e.g. Example goes here too to bring to life the definition)',
    aggregatedData: 'Aggregated data',
    aggregatedDataDetail: 'TBC copy goes here (e.g. Example goes here too to bring to life the definition)',
    derivedData1: 'Derived data',
    derivedDataDetail: 'TBC copy goes here (e.g. Example goes here too to bring to life the definition)',
    clientAgencyHeader2: 'Agreement',
    theTerms: 'The terms',
    theTermsInfo: 'Duration of contract',
    fixedValue: 'Fixed',
    rollingValue: 'Rolling',
    autoRenewValue: 'AutoRenew',
    fixedContractinfo: 'With fixed start and end dates, you will be notified when you need to renew the contract.',
    fixedContract: 'Fixed start / end dates',
    fixedContractFieldLabel: 'Start/end dates',
    fixedContractStartDate: 'Start date',
    fixedContractEndDate: 'End date',
    rollingContract: 'Rolling contract after initial term',
    rollingContractInfo: 'If this rolling contract changes, you will need to update contract terms in settings at a later date, when a new contract is renegotiated.',
    autoRenewContract: 'Auto-renew on a specific date',
    autoRenewContractFieldLabel: 'Auto renew every',
    clientContacts: 'contact details at ', // clinet name will come after that
    clientContactsInfo: ' important those involved in this setup process have access to these client',
    card1Title: 'Add client lead',
    card2Title: 'Add procurement',
    card3Title: 'Add legal',
    clientContactFormTitle: 'Client contact- ', // card title name will come after that
    clientContactFormName: 'Full name',
    clientContactFormEmail: 'Client contact email',
    clientContactFormJobTitle: 'Job title',
    dataUsage: 'Data usage',
    rightToUseData: 'Right to use data',
    rightInfo: 'Has the right to use data been made clear in the contract?',
    right1: 'has been granted right to use data ONLY for the provision of services.',
    right2: 'has been granted right to use data for the provision of services AND',
    right3: 'The contract is silent — no rights have been specified.',
    right1Info: ' aggregate data reporting across clients for any reasons.',
    right2Info: ' aggregate data reporting across clients for internal business purposes.',
    right3Info: ' aggregate data reporting across clients for internal business purposes (and potentially in a broader sense).',
    rightToAggData: 'Right to aggregate data across clients',

    aggDataInfo: '(When we say “aggregate” data, we mean combining data across client brands, client sub-brands and territories or across clients.)',
    aggDataQues: 'have permission to aggregate data across different clients?',
    aggDataOption1: 'will ONLY be able to report at a brand (e.g. Gillette) or sub-brand level (e.g. Gillette Venus) within a market (e.g. UK).',
    aggDataOption2: 'will be able to aggregate data across brands (e.g. Gillette), sub-brands (e.g. Gillette Venus), markets (e.g. UK) and market territory groups/regions (e.g. London and the South East).',
    aggDataOption3: 'will be able to aggregate data across brands(e.g. Gillette), sub-brands (e.g. Gillette Venus), markets (e.g. UK) and market territory groups/regions (e.g. London and the South East) and across multiple clients (e.g. Procter & Gamble and Unilever) to complete sector analysis, country market analysis, monitor, spend.',
    ownershipOfData: 'Ownership of generated data',
    generatedData: '(When we say generated data we mean data generated from the campaigns we set up for our clients.)',
    owner: 'Who is the owner of generated data?',
    generatedDataOption1: 'Client (or a third party) owns this data.',
    generatedDataOption2: 'owns this data.',
    rightAndPermission: 'Rights and permissions to derive data from campaign data',
    derivedDataInfo: 'obtain, acquire, extract or glean from the generated data collected from third parties.)',
    derivedDataQues: 'permitted to use derived data?',
    derivedOption1: 'Yes — there is an explicit reference to creating derived data.',
    derivedOption2: 'YES — client is silent on being able to create derived data.',
    derivedOption3: 'No — there is an explicit restriction against deriving data.',
    restrictionInfo: 'If you select this option, it means you will not be able to derive data beyond what has been supplied by the media vendors/partners. This would prevent users being able to effectively transform and clean data within the data refinery applications, deriving values within taxonomy applications and deriving insight for our clients. Reporting would need to be done all on raw data.',
    restrictionInfo1: 'If this is a problem, you should seek advice via your Client lead to review renegotiation of this contract.',
    restrictionQues: 'Who is the owner of derived data?',
    restrictionOption1: 'Client',
    restrictionOption2: '[Agency name]',
    permissionQues: 'Who has permission to use derived data?',
    permissionOption1: '[Agency name] can use it for their own purpose with NO RESTRICTIONS.',
    permissionOption2: '[Agency name] can ONLY use it for the provision of services for this Client ONLY.',
    permissionOption3: '[Agency name] can ONLY use it for the provision of services for this Client AND across clients (providing it is anonymised).',
    anonymizeData: 'Does derived data always need to be anonymised?',
    contactClientLead: 'Client lead',
    procurement: 'Procurement',
    legal: 'Legal',
    lawPageHeader: 'Governing law and data storage restrictions',
    governingLawOfAgreement: 'Governing law of agreement',
    governingLawOfAgreementDescription: '(The territory-based governing law that applies to the whole of this global master agreement)',
    governingLawOfAgreementFieldTitle: 'Which governing law applies to this agreement?',
    dataStorageRestrictions: 'Data storage restrictions',
    dataStorageRestrictionsDescription1_1: 'Please note, all data stored in the dpgs will be hosted on ',
    dataStorageRestrictionsDescription1_2: 'For MVP, this will be using Microsoft Azure, and in future we will rollout ',
    // dataStorageRestrictionsDescription2:"Please contact [xxxxx@mediaecosystem.com] if cloud storage is not permitted under the agreement.",
    // dataStorageRestrictionsDescription3_1:"For MVP, this will be using Microsoft Azure, and in future we will rollout",
    // dataStorageRestrictionsDescription3_2:" alternative cloud providers ",
    // dataStorageRestrictionsDescription3_3:"in 2020.)",
    dataStorageRestrictionsSubQuestion1: 'Does the contract restrict the physical locations of servers used to store data?',
    dataStorageRestrictionsSubQuestion1_No: 'No',
    dataStorageRestrictionsSubQuestion1_Yes1: 'Yes — countries are specified where servers MUST be stored.',
    dataStorageRestrictionsSubQuestion1_Yes2: 'Yes — countries are specified where servers MUST NOT be stored.',
    dataStorageRestrictionsSubQuestion2: 'Select the country/countries where servers MUST be stored',
    dataStorageRestrictionsSubQuestion2_a: 'Select the country/countries where servers MUST NOT be stored',
    dataStorageRestrictionsSubQuestion2a: 'Country/countries where servers MUST NOT be stored',
    dataStorageRestrictionsSubQuestion3: 'If this is an EMEA client, are there locations outside the European Economic Area (EEA), where data is allowed to be stored?',
    dataStorageRestrictionsSubQuestion3_No: 'No',
    dataStorageRestrictionsSubQuestion3_Yes: 'Yes',
    dataStorageRestrictionsSubQuestion3_NotApplicable: 'Not applicable',
    dataStorageRestrictionsSubQuestion4: 'Select the country/countries outside European Economic Area (EEA) where data is allowed to be stored.',
    dataStorageRestrictionsSubQuestion5: 'Are there specific security measures the client has requested in the contract to protect data, that are not listed below?',
    dataStorageRestrictionsSubQuestion5_2: 'Data governance is in-built into this client management process which is enforced and/or available for all users of the ecosystem.',
    dataStorageRestrictionsSubQuestion5_3: 'We securely store a client\'s data (and our own), by keeping it logically separated at rest.',
    dataStorageRestrictionsSubQuestion5_4: 'We have implemented a robust and flexible identity and access management application (called User Management) that enables certain users to create and manage teams; so the right people have access to data on this account.',
    dataStorageRestrictionsSubQuestion5Description_Heading: 'ALL data will be stored logically separated in secure location/s on servers using cloud provider storage.',
    dataStorageRestrictionsSubQuestion5Description_1: 'This means, when data is at rest it is stored separately from any other client\'s data to keep it secure. Cloud providers offer easy maintenance, the data itself is backed-up remotely in case of outages or failures, and can be made available to users faster over the internet.',
    //dataStorageRestrictionsSubQuestion5Description_2:"Cloud storage ensure's robust, high performance; where data can be loaded only when it is needed. Cloud provides offer easy maintainance, the data itself is backed-up remotely in case of outages or failures, and can be made available to users faster over the internet.",
    pleaseNote_1: 'Please note',
    pleaseNote_2: 'Please note if the contract is silent, please infer an answer.',
    //iConfirm:"I understand how data will be stored in the platform and confirm this is permitted under the contract.",
    iConfirm: 'I confirm the client agrees to logical separation of data via cloud storage.',
    cloudStorageTooltip: 'Cloud storage is the service model in which data is maintained, managed, backed up remotely on servers and made available to users over a network (typically the Internet).',
    alternativeCloudProvidersTooltip: 'Cloud storage is the service model in which data is maintained, managed, backed up remotely on servers and made available to users over a network (typically the Internet).',
    governance: 'Client data governance',
    confirmCancel: 'Confirm cancel',
    cancelDesc: 'All progress will be deleted. Do you want to save your progress?',
    basicDetails: 'Store the basic details about the client',
    recordDetails: 's data according to the contract',
    //governanceDetail: ". It is your responsibility to ensure this record is accurate which will be reviewed by the authorisors opposite.",
    makeSure: 'Make sure:',
    actualContract: 'You have the contract',
    toBeReviewed: 'To be accurate as this will be reviewed by legal and finance',

    approvalsPageHeader: 'Approvals and service provision restrictions',
    dataAccessApproval: 'Data access approval',
    dataAccessApprovalDescription: '(This section refers to whether approval is needed from the client).',
    dataAccessApprovalQuestion1: 'Is the client required to grant approval to those that need to access data for the provision of services?',
    dataAccessApprovalQuestion2: 'Select the options that ARE APPROVED to access client',
    dataAccessApprovalQuestion2_Checkbox1: 'that is stipulated in the contract).',
    dataAccessApprovalQuestion2_Checkbox2: 'Platforms such as Amnet for buying',
    dataAccessApprovalQuestion2_Checkbox3: 'Third party media vendors/partners and sites',
    dataAccessApprovalQuestion2_Checkbox4: 'Subcontracted data providers/companies or software companies (e.g. Nielsen)',
    dataAccessApprovalQuestion2_Checkbox5: 'Staff working on the account',
    serviceProvision: 'Service provision',
    serviceProvisionQuestion1: 'Are there any restrictions explicitly mentioned within the contract regarding the service provision of this client?',
    //serviceProvisionQuestion1:"Are auditing rights explicitly refrenced in the contract?",
    serviceProvisionDescription: '(Definition required here.)',
    serviceProvisionQuestion2: 'If yes, select ALL options that apply.',
    serviceProvisionQuestion2_Checkbox1: 'affiliates/entities are allowed service provision.',
    serviceProvisionQuestion2_Checkbox2: 'Other supporting Dentsu Aegis Network agencies in the market countries this client will be present or are serviced from.',
    serviceProvisionQuestion3: 'Are there any additional agencies who will provide the services and ARE named in the contract?',
    serviceProvisionQuestion3_a: 'Are there any additional agencies who will provide the services and ARE named in the contract?',
    serviceProvisionQuestion4: 'Select supporting agency/agencies',
    dataArchivingPotability: 'Data archiving, portability and retention',
    dataArchiving: 'Data archiving',
    backups: '(Backups and storage)',
    archivingQues: 'Is data allowed to be kept in a backup or archive (separate from cloud storage)?',
    dataPortability: 'Data portability',
    tbcCopy: '(Ability to transfer data to a client)',
    obligations: 'Are there obligations by which dpgs must deliver data on request, in a particular format?',
    noFormat: 'No explicit formats are specified in the contract.',
    yesIndustryFormat: 'Yes — industry standard formats are referenced in the contract.',
    yesSpecificFormat: 'Yes — client has specified formats for delivery of data',
    fileTypes: 'Specified formats or file types',
    obligationTimeFrame: 'Are there obligations by which dpgs must deliver data on request, in a particular timeframe?',
    noTimeframes: 'No timeframes are specified in the contract.',
    yesTimeframe: 'Yes — client has specified timeframes for delivery of data.',
    timeframe: 'Timeframe data must be delivered within',
    days: 'days',
    dataRetentionHeader: 'Data retention',
    dataRetentionQuestion1: 'retain data following termination/end of life of a contract?',
    duration: '(How long data can be retained in the case to termination/end of life of a contract).',
    note: 'if the contract is silent, data by default will be retained for 3 years, and automatically deleted thereafter.',
    retentionPoint1: ' must delete immediately by the date of termination.',
    retentionPoint2: ' must delete within a specified time period.',
    selectTimePeriod: 'Time period',
    auditingHeader: 'Auditing',
    auditRights1: 'Auditing rights',
    auditReference: 'Does the contract mention auditing rights?',
    auditTrail: 'Should an audit trail of how data is used and accessed be made available to the client?',
    thirdPartyAuditor: 'Can third party auditors access data?',
    auditCompliance: 'Can the client (or its representatives) audit compliance with data-related obligations (either specifically or as part of general compliance)?',
    auditingFrequency: 'Auditing frequency',
    frequencyInfo: '(Frequency of auditing may not be explicitly referenced within your contract — that\'s ok. You can change these settings at a later date).',
    auditQues: 'Does the contract mention auditing frequency?',
    media: 'Media time period',
    // timePeriod: "Time period",
    financial1: 'Financial time period',
    security1: 'Security time period',
    review: 'Review before submission',
    mediaTimePeriod: 'Media time period',
    financialTimePeriod: 'Financial time period',
    securityTimePeriod: 'Security time period',
    accountHeader: 'Client account settings',
    accountInfo: 'The final hurdle - where you define the brands and/or sub-brands/products, reporting groups and settings',
    accountDesc1: 'This is the last part now - where it\'s vital to orgainse the account according to how you wish to report for this client.',
    accountDesc2: 'into smaller brand parts; for reporting purposes and for dividing your teams responsibilities so you can govern user access permissions easily (who can work on what).',
    createGroups: 'Create groups',
    groupDesc: 'It might help to structure and/or segregate account and reporting activity. You can group the follwing accounts:',
    groupQues: 'Do you want to create group ?',
    groupInfo: 'Some clients require reporting on region by region basis. Groups help to structure an account for more accurate reporting and managing user permissions.',
    groupHeader: 'Name a group and assign accounts to it',
    groupTitle: 'Group title',
    accountGroups: 'Account groups',
    accountGroup: 'Account groups',
    accountSubGroup: 'Account subgroups',
    addClientSubBrand: 'Add Client sub-brands',
    brandInfo: 'This allows to structure an account for more accurate reporting and managing user permissions.',
    addBrand: 'Add sub-brands for',
    brandTitle: 'Sub-brand title',
    globalSetting: 'Global reporting settings for all accounts',
    lang: 'Default language',
    currency: 'Default currency',
    timezone: 'activeScreenText',
    fiscalYr: 'Fiscal year start date',
    timezoneDesc: 'Time is use to standardise reporting on this account when scheduling connections to data sources',
    fiscalYear: 'Select fiscal year start date',
    localSettings: 'Are local settings required for this account?',
    agree: 'You are agreeing that local markets can override the global settings for an account',
    agreeInfo: 'If you are not a market lead, you can assign one in ',
    financeMsg: 've authorised the financial part',
    legalLeft: 'will now complete the legal authorisation part.',
    legalMsg: 've authorised the legal part',
    legalDone: 'The account lead will finish the process by adding account settings.',
    legalPointer1: 'To have the legal contract or summary available to cross-reference',
    legalPointer2: 'This record needs to be accurate from a legal perspective.',
    legalPointer3: 'To send back for amendments if you spot any discrepancies',
    allFinished: 'All finished!',
    accountDone: 'Your account settings have been added to the account and we now have all the details we need at this stage.',
    assignedMsg: 'Currently you don\'t have any accounts assigned to you. Please come back later. ',
    activeMsg: 'Accounts appear hereas soon as a legal authoriser approves client and data governance details',
    ammendmentMsg: 'As soon as you start adding client details to an account, it will appear here.',
    progressMsg: 'As soon as you start adding client details to an account, it will appear here.',
    contentOfTnC: '<div style = \'margin-left:25px;font-family: monospace;\'><p><br><br> <h2 style = \'display: inline;font-family: monospace;\'> Global Data Platform<br> Terms of Service Agreement <\/h2><br> <\/p><br><h3 style = \'font-family: monospace;\'>Welcome to Dentsu Aegis Network Global Data Platform!<\/h3> <br><p style = \'font-family: monospace;\'>Thanks for using our products and services (\u201CServices\u201D). The Services are provided by Dentsu Aegis Network Ltd. (\u201CDentsu Aegis\u201D), located at Regent\u2019s Place, 10 Triton Street, London, NW1 3BF, United Kingdom. By using our Services, you are agreeing to these terms. Please read them carefully. Our Services are very diverse, so sometimes additional terms or product requirements (including age requirements) may apply. Additional terms will be available with the relevant Services and those additional terms become part of your agreement with us if you use those Services. <br><\/p><br> <h3 style = \'font-family: monospace;\'>Using our Services<\/h3><br><p style = \'font-family: monospace;\'>You must follow any policies made available to you within the Services. Do not misuse our Services, for example, do not interfere with our Services or try to access them using a method other than the interface and the instructions that we provide. You may use our Services only as permitted by law, including applicable export and control laws and regulations. We may suspend or stop providing our Services to you if you do not comply with our terms or policies or if we are investigating suspected misconduct. Using our Services does not give you ownership of any intellectual property rights in our Services or the content that you access. You may not use content from our Services unless you obtain permission from its owner or are otherwise permitted by law. These terms do not grant you the right to use any branding or logos used in our Services. Do not remove, obscure or alter any legal notices displayed in or along with our Services. Our Services display some content that is not Dentsu Aegis\u2019s. This content is the sole responsibility of the entity that makes it available. We may review content to determine whether it is illegal or violates our policies, and we may remove or refuse to display content that we reasonably believe violates our policies or the law. But that does not necessarily mean that we review content, so please do not assume that we do. In connection with your use of the Services, we may send you service announcements, administrative messages and other information. You may opt out of some of those communications. Some of our Services are available on mobile devices. Do not use such Services in a way that distracts you and prevents you from obeying traffic or safety laws. <\/p><br> <h3 style = \'font-family: monospace;\'>Modifying and Terminating our Services<\/h3><\/br><p style = \'font-family: monospace;\'>We are constantly changing and improving our Services. We may add or remove functionalities or features and we may suspend or stop a Service altogether. You can stop using our Services at any time, although we would be sorry to see you go. Dentsu Aegis may also stop providing Services to you or add or create new limits to our Services at any time. We believe that you own your data, and preserving your access to such data is important. If we discontinue a Service, where reasonably possible, we will give you reasonable advance notice and a chance to remove information from that Service. <\/p> <br><h3 style = \'font-family: monospace;\'>Our Warranties and Disclaimers<\/h3><br><p style = \'font-family: monospace;\'>We provide our Services using a commercially reasonable level of skill and care and we hope that you will enjoy using them. But there are certain things that we do not promise about our Services. Other than as expressly set out in these terms or additional terms, neither Dentsu Aegis nor its suppliers or distributors makes any specific promises about the Services. For example, we do not make any commitments about the content within the Services, the specific functions of the Services or their reliability, availability or ability to meet your needs. We provide the Services \u201Cas is\u201D. Some jurisdictions provide for certain warranties, like the implied warranty of merchantability, fitness for a particular purpose and noninfringement. To the extent permitted by law, we exclude all warranties. <\/p> <br><h3 style = \'font-family: monospace;\'>About these Terms<\/h3><br><p style = \'font-family: monospace;\'>We may modify these terms or any additional terms that apply to a Service to, for example, reflect changes to the law or changes to our Services. You should look at the terms regularly. We\u2019ll post notice of modifications to these terms on this page. We\u2019ll post notice of modified additional terms in the applicable Service. Changes will not apply retrospectively and will become effective no earlier than fourteen days after they are posted. However, changes addressing new functions for a Service or changes made for legal reasons will be effective immediately. If you do not agree to the modified terms for a Service, you should discontinue your use of that Service. If there is any inconsistency between these terms and the additional terms, the additional terms will prevail to the extent of the inconsistency. These terms govern the relationship between Dentsu Aegis and you. They do not create any third-party beneficiary rights. If you do not comply with these terms and we do not take action immediately, this doesn\u2019t mean that we are giving up any rights that we may have (such as taking action in the future). If it turns out that a particular term is not enforceable, this will not affect any other terms. <\/p> <\/div>',
    clientName: 'Client Name',
    leadBrand: 'Lead agency brand',
    leadResponsibility: 'Enter the lead agency client responsibilities',
    suppAgency: 'Supporting agencies',
    registeredName: 'Registered Names',
    clientNameDesc: 'Legal name of the client',
    leadBrandDesc: 'Lead agency brand',
    leadResponsibilityDesc: 'Lead agency client responsibilities',
    suppAgencyDesc: 'Supporting agencies',
    registeredNameDesc: 'Registered Names',
    termOfContract: 'Term of contract : End Date',
    jurisdictionLaw: 'Jurisdiction/governing law for this client',
    territoryLaw: 'Territory law for this client',
    masterAgreement: 'Master agreement for this account',
    typeOfContract: 'Type of contract agreement',
    termOfContractDesc: 'Term of contract : End Date',
    jurisdictionLawDesc: 'Jurisdiction/governing law for this client',
    territoryLawDesc: 'Territory law for this client',
    masterAgreementDesc: 'Master agreement for this account',
    typeOfContractDesc: 'Type of contract agreement',
    financeApprover: 'Finance Approver',
    legalApprover: 'Legal Approver',
    brandApprover: 'Agency Brand Approver',
    clientContact: 'Client Contact',
    clientLead: 'Client Lead',
    financeApproverDesc: 'Finance Approver email id',
    legalApproverDesc: 'Legal Approver email id',
    brandApproverDesc: 'Agency Brand Approver name',
    clientContactDesc: 'Client Contact email id',
    clientLeadDesc: 'Client Lead email id',
    auditRights: 'What parties have audit rights over:',
    financeCode: 'Finance Code',
    auditRightsDesc: 'Audit rights for various entities',
    financeCodeDesc: 'Finance Code',
    legalOwner: 'Who is the legal owner of the data?',
    dataPortabilityEndDate: 'Data Portability Period End Date',
    legalOwnerDesc: 'Who is the legal owner of the data?',
    dataPortabilityEndDateDesc: 'Data Portability Period End Date',
    markets: 'Legitimate regions/markets data can reside in',
    dataSegregation: 'Data segregation',
    cloudProvider: 'Approved cloud provider',
    securityStorage: 'Type of security needed for storage',
    encryption: 'What type of cryptographic encryption is required?',
    restEncryption: 'What type of cryptographic encryption is required at Rest?',
    transitEncryption: 'What type of cryptographic encryption is required in Transit?',
    marketsDesc: 'Legitimate regions/markets data can reside in',
    dataSegregationDesc: 'Data segregation',
    cloudProviderDesc: 'Approved cloud provider',
    securityStorageDesc: 'Type of security needed for storage',
    encryptionDesc: 'Type of cryptographic encryption required',
    restEncryptionDesc: 'Type of cryptographic encryption required at rest',
    transitEncryptionDesc: 'Type of cryptographic encryption required in transit',
    subsidiaries: 'Approved Dentsu Aegis Network subsidiaries that can use the data',
    partyUsingData: 'Approved 3rd/4th parties that can use the data',
    archiveDate: 'Archive Date',
    ownerOfDerivedData: 'Owner of derived data and metadata',
    ownerOfDerivedDataDesc: 'Owner of derived data and metadata',
    restrictionsOfDerivedData: 'Restrictions of derived data and metadata',
    restrictionsOfDerivedDataDesc: 'Restrictions of derived data and metadata',
    retrictions: 'Restrictions and Inclusions',
    typeOfDataForClient: 'What types of data can the client access?',
    typeOfDataForClientDesc: 'What types of data can the client access?',
    typeOfDataForDAN: 'What types of data can the Dan-Team access?',
    typeOfDataForDANDesc: 'What types of data can the Dan-Team access?',
    confidentialityAgreement: 'What type of confidentiality agreements within Dentsu Aegis Network are required to be signed before users can work on this client account?',
    auditRightsHeader: 'Audit Rights',
    dataAccessLocations: 'Data access locations',
    gdpr: 'GDPR',
    financial: 'Financial',
    performance: 'Performance',
    security: 'Security',
    periodEndDate: 'Period End Date',
    /*
        subsidiariesDesc = Approved Dentsu Aegis Network subsidiaries that can use the data
        partyUsingDataDesc = Approved 3rd/4th parties that can use the data
        archieveDateDesc = Archieve Date
        periodEndDateDesc = Period End Date
        clientCompetitors = Are there any client competitors within Dentsu Aegis Network, teammembers working on this account not allowed to work with?
        confidentialityAgreementDesc = What type of confidentiality agreements\nwithin Dentsu Aegis Network are\nrequired to be signed before users\ncan work on this client account?
        clientCompetitorsDesc = Are there any client competitors\nwithin Dentsu Aegis Network,\nteam members working on this account\nnot allowed to work with?*/
    dataType: 'Data Type',
    supplierInclusion: 'Supplier Inclusion',
    dataTypeDesc: 'Data Type',
    supplierInclusionDesc: 'Supplier Inclusion',
    usageRights: 'Usage Rights:',
    personal: 'Personal',
    nonPersonal: 'Non - Personal',
    usageRightsDesc: 'Usage Rights',
    dataAccessLocationsDesc: 'Data access locations',
    personalDesc: 'Personal',
    nonPersonalDesc: 'Non Personal',
    // gdpr: "GDPR",
    // financial: "Financial",
    // performance: "Performance",
    // security: "Security",

    agreementDetails: 'The Agreement',
    approverDetails: 'Approvers',
    //  contactDetails: "Client Contact Details",
    financePolicies: 'Finance Policies',
    auditing: 'Audit Rights',
    ownership: 'Who Owns The Data?',
    dataStorage: 'Data Storage',
    dataSecurity: 'Data Security and Encryption',
    dataSharing: 'Data Sharing and Approval',
    dataRetention: 'Data Retention',
    derivedData: 'Derived Data and MetaData',
    permission: 'Who has permission to use derived data and metadata',
  },

  vendorManagement: {
    reviewAndConfirmPageParagraph: (clientName) => 'You are about to add the following vendor to ' + clientName + '. Please check that everything is correct and read the confirmation below',
    reviewAndConfirmPageSubParagraph: (clientName) => 'By adding this vendor to ' + clientName + ' you are allowing DAN to use it to run campaigns for ' + clientName + ' in the markets specified. Please confirm you are happy to go ahead',
    selectMarketPageErrorHeader: (marketsCount) => 'You can\'t select the following ' + marketsCount + ' markets as they are not currently available for this vendor',

    particularVendorPageText: {
      feedHeader: 'Vendor agreements',
      headMarketsValue: 'Markets',
      headAgreementTypeValue: 'Agreement Type',
      headStatusValue: 'Status',
      viewDetailsButton: 'View details',
    },

    AgreementsPopupUIText: {
      agreementsHeader: 'Vendor Agreement Details',
      secondHeader: 'Data usage summary',
      businessUnitOwner: 'Business unit owner',
      agreementType: 'Agreement type',
      marketsServed: 'Markets served',
      contractTermType: 'Contract term type',
      contractStartDate: 'Contract start date',
      contractEndDate: 'Contract end date',
      oneTrustAssured: 'OneTrust Assured',
      connectorType: 'Connector type',
      derivedDataOwner: 'Derived data owner',
      reportingDataOwner: 'Reporting data owner',
      allowedToBeCollected: 'Allow personal data allowed to be collected',
      allowDataBeAggregated: 'Allow data be aggregated',
      availableToClients: 'Allow raw data be available to clients',
      outsideOfThePlatform: 'Allow data be used outside of the platform',
      streamDataLicensing: 'Allow bid stream data licensing',
      danAffiliates: 'Allow data use by other DAN affiliates',
    },
  },
};
module.exports = CmsContext;
